---
- name: Create mariadb docker-compose folder
  ansible.builtin.file:
    path: /home/{{ docker_user }}/mariadb
    state: directory
    owner: 0
    group: 0
    mode: "0755"

- name: Copy compose file
  ansible.builtin.copy:
    src: roles/bdd/templates/docker-compose.yml
    dest: /home/{{ docker_user }}/mariadb/docker-compose.yml
    owner: 0
    group: 0
    mode: "0644"

- name: Start mariadb container
  community.docker.docker_compose_v2:
    project_src: /home/{{ docker_user }}/mariadb
    state: present
  become: true
  become_user: "{{ docker_user }}"