apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: workshop

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: workshop-backend:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          env:
            - name: PORT
              value: "3000"

            - name: DB_HOST
              value: "mariadb"

            - name: DB_PORT
              value: "3306"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_DATABASE