---
- name: Install various basic tools
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - docker.io
      - docker-compose

- name: S'assurer que le service Docker est démarré et activé au boot
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: S'assurer que le groupe docker existe
  ansible.builtin.group:
    name: docker
    state: present

- name: Add G8 to the docker group
  ansible.builtin.user:
    name: G8
    groups: docker
    append: yes