USE Workshop;

CREATE TABLE IF NOT EXISTS sensors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    device VARCHAR(50) NOT NULL,
    temp DECIMAL(5,2),
    hum DECIMAL(5,2),
    gaz INT,
    pir TINYINT(1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fingerprints (
    id INT AUTO_INCREMENT PRIMARY KEY,
    device VARCHAR(50) NOT NULL,
    event VARCHAR(50) NOT NULL,
    user_id INT,
    confidence INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS commands (
    id INT AUTO_INCREMENT PRIMARY KEY,
    action_id VARCHAR(50),
    motor INT,
    auto_mode BOOLEAN,
    servo INT,
    unlock_door BOOLEAN,
    led VARCHAR(10),
    alarm_off BOOLEAN,
    message VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,

    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,

    first_name VARCHAR(50),
    last_name VARCHAR(50),

    photo VARCHAR(255),

    role ENUM('ADMIN', 'USER', 'SECURITY') DEFAULT 'USER',

    fingerprint_id VARCHAR(100) UNIQUE,

    status ENUM('ACTIVE', 'INACTIVE', 'BLOCKED') DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;